/* Datos base editables. El separador de categorías es coma, punto y coma o barra vertical. */
window.SDC_CONFIG = {
  storeName: 'SD COMAYAGUA',
  whatsapp: '+504 3151-7755',
  whatsappNumber: '50431517755',
  accessKey: '199311',
  codPercent: 6,
  lowStockLimit: 3,
  currency: 'Lps.',
  sheetId: '1ISLGulvbwZuTYhI0pyuLiIq0Ntl_x5y0K0Um1gOb32U',
  productSheet: 'productos_pos',
  autoSheetSync: true,
  webAppUrl: 'https://script.google.com/macros/s/AKfycbzZKAqIR_u-rmcdDUodffpLtZb5zFXOXms8MEcbN0zkfvXhEUe_MQE49dyAtDzaTkWY/exec'
};

window.SDC_DEPARTMENTS = [
  'Atlántida','Colón','Comayagua','Copán','Cortés','Choluteca','El Paraíso','Francisco Morazán','Gracias a Dios','Intibucá','Islas de la Bahía','La Paz','Lempira','Ocotepeque','Olancho','Santa Bárbara','Valle','Yoro'
];

window.SDC_MUNICIPALITIES = {
  'Atlántida':['La Ceiba','El Porvenir','Esparta','Jutiapa','La Masica','San Francisco','Tela','Arizona'],
  'Colón':['Trujillo','Balfate','Iriona','Limón','Sabá','Santa Fe','Santa Rosa de Aguán','Sonaguera','Tocoa','Bonito Oriental'],
  'Comayagua':['Comayagua','Ajuterique','El Rosario','Esquías','Humuya','La Libertad','Lamaní','La Trinidad','Lejamaní','Meámbar','Minas de Oro','Ojos de Agua','San Jerónimo','San José de Comayagua','San José del Potrero','San Luis','San Sebastián','Siguatepeque','Villa de San Antonio','Las Lajas','Taulabé'],
  'Copán':['Santa Rosa de Copán','Cabañas','Concepción','Copán Ruinas','Corquín','Cucuyagua','Dolores','Dulce Nombre','El Paraíso','Florida','La Jigua','La Unión','Nueva Arcadia','San Agustín','San Antonio','San Jerónimo','San José','San Juan de Opoa','San Nicolás','San Pedro','Santa Rita','Trinidad de Copán','Veracruz'],
  'Cortés':['San Pedro Sula','Choloma','Omoa','Pimienta','Potrerillos','Puerto Cortés','San Antonio de Cortés','San Francisco de Yojoa','San Manuel','Santa Cruz de Yojoa','Villanueva','La Lima'],
  'Choluteca':['Choluteca','Apacilagua','Concepción de María','Duyure','El Corpus','El Triunfo','Marcovia','Morolica','Namasigüe','Orocuina','Pespire','San Antonio de Flores','San Isidro','San José','San Marcos de Colón','Santa Ana de Yusguare'],
  'El Paraíso':['Yuscarán','Alauca','Danlí','El Paraíso','Güinope','Jacaleapa','Liure','Morocelí','Oropolí','Potrerillos','San Antonio de Flores','San Lucas','San Matías','Soledad','Teupasenti','Texiguat','Vado Ancho','Yauyupe','Trojes'],
  'Francisco Morazán':['Distrito Central','Alubarén','Cedros','Curarén','El Porvenir','Guaimaca','La Libertad','La Venta','Lepaterique','Maraita','Marale','Nueva Armenia','Ojojona','Orica','Reitoca','Sabanagrande','San Antonio de Oriente','San Buenaventura','San Ignacio','San Juan de Flores','San Miguelito','Santa Ana','Santa Lucía','Talanga','Tatumbla','Valle de Ángeles','Villa de San Francisco','Vallecillo'],
  'Gracias a Dios':['Puerto Lempira','Brus Laguna','Ahuas','Juan Francisco Bulnes','Ramón Villeda Morales','Wampusirpi'],
  'Intibucá':['La Esperanza','Camasca','Colomoncagua','Concepción','Dolores','Intibucá','Jesús de Otoro','Magdalena','Masaguara','San Antonio','San Isidro','San Juan','San Marcos de la Sierra','San Miguel Guancapla','Santa Lucía','Yamaranguila','San Francisco de Opalaca'],
  'Islas de la Bahía':['Roatán','Guanaja','José Santos Guardiola','Utila'],
  'La Paz':['La Paz','Aguanqueterique','Cabañas','Cane','Chinacla','Guajiquiro','Lauterique','Marcala','Mercedes de Oriente','Opatoro','San Antonio del Norte','San José','San Juan','San Pedro de Tutule','Santa Ana','Santa Elena','Santa María','Santiago de Puringla','Yarula'],
  'Lempira':['Gracias','Belén','Candelaria','Cololaca','Erandique','Gualcince','Guarita','La Campa','La Iguala','Las Flores','La Unión','La Virtud','Lepaera','Mapulaca','Piraera','San Andrés','San Francisco','San Juan Guarita','San Manuel Colohete','San Rafael','San Sebastián','Santa Cruz','Talgua','Tambla','Tomalá','Valladolid','Virginia','San Marcos de Caiquín'],
  'Ocotepeque':['Ocotepeque','Belén Gualcho','Concepción','Dolores Merendón','Fraternidad','La Encarnación','La Labor','Lucerna','Mercedes','San Fernando','San Francisco del Valle','San Jorge','San Marcos','Santa Fe','Sensenti','Sinuapa'],
  'Olancho':['Juticalpa','Campamento','Catacamas','Concordia','Dulce Nombre de Culmí','El Rosario','Esquipulas del Norte','Gualaco','Guarizama','Guata','Guayape','Jano','La Unión','Mangulile','Manto','Salamá','San Esteban','San Francisco de Becerra','San Francisco de la Paz','Santa María del Real','Silca','Yocón','Patuca'],
  'Santa Bárbara':['Santa Bárbara','Arada','Atima','Azacualpa','Ceguaca','Concepción del Norte','Concepción del Sur','Chinda','El Níspero','Gualala','Ilama','Las Vegas','Macuelizo','Naranjito','Nuevo Celilac','Petoa','Protección','Quimistán','San Francisco de Ojuera','San José de Colinas','San Luis','San Marcos','San Nicolás','San Pedro Zacapa','San Vicente Centenario','Santa Rita','Trinidad'],
  'Valle':['Nacaome','Alianza','Amapala','Aramecina','Caridad','Goascorán','Langue','San Francisco de Coray','San Lorenzo'],
  'Yoro':['Yoro','Arenal','El Negrito','El Progreso','Jocón','Morazán','Olanchito','Santa Rita','Sulaco','Victoria','Yorito']
};

window.SDC_DEFAULT_PRODUCTS = [
  {
    "id": "SDC-001",
    "name": "Dedales o Fundas para Dedos",
    "categories": "Dedales",
    "brand": "",
    "price": 25,
    "cost": 8,
    "stock": 216,
    "image": "https://scontent.ftgu2-2.fna.fbcdn.net/v/t45.5328-4/677652330_1500160691729334_4118015065856447884_n.jpg?stp=dst-jpg_p960x960_tt6&_nc_cat=107&ccb=1-7&_nc_sid=247b10&_nc_eui2=AeHOXzeWwS8JnqwSlyAzqpSvqSikc0bVu0ypKKRzRtW7TFx0OsnlAcWUPoESVbBUbnWjTdTH8AOEU_Dpt0grcjTf&_nc_ohc=Eu6K10t0270Q7kNvwF_EGTz&_nc_oc=Adp59PX6FuzWv9K0B0EcRp4Bj04hOIrLLxAfDB04g4CuUY1OCfyol2q-ZfBySBYPB5o&_nc_zt=23&_nc_ht=scontent.ftgu2-2.fna&_nc_gid=OjSpZ7JjINzjcwKmoKCRTQ&_nc_ss=7b2a8&oh=00_Af4XyFV9Yrv_vWh2CezlRQ0FHHT-av11Tutqk1yprkHBvQ&oe=69FD3C6C",
    "gallery": "",
    "description": "Dedales gamer para celular, ideales para jugar con mejor deslizamiento, comodidad y precisión. Ayudan a reducir el sudor en pantalla y funcionan muy bien para Free Fire, PUBG Mobile, Call of Duty Mobile y otros juegos táctiles.",
    "promos": "1=25 | 2=50 | 3=69 | 4=92 | 5=110 | 6=132 | 7=154 | 8=168 | 9=189 | 10=200",
    "updatedAt": "2026-05-10T23:02:09.262Z",
    "active": true
  },
  {
    "id": "SDC-002",
    "name": "Gatillos Gamer Pro / Triggers Pro para celular",
    "categories": "Gamer Móvil",
    "brand": "",
    "price": 400,
    "cost": 190,
    "stock": 12,
    "image": "https://scontent.ftgu2-2.fna.fbcdn.net/v/t45.5328-4/676041307_1622203069066456_833207036229297481_n.jpg?stp=dst-jpg_p960x960_tt6&_nc_cat=102&ccb=1-7&_nc_sid=247b10&_nc_eui2=AeF1LpcG2ri2R6BK98WklS8WLaI0EGwoyC0tojQQbCjILUIr3DzyFRM3mRk8YlU_bSjsiNU3ramv9chW3Cf55Ipx&_nc_ohc=EvmNhQh0PGYQ7kNvwG0FjQD&_nc_oc=AdpTc1H49mRkgUooNvg7BQfR1hVVVHr7Vl7mS2-DIv4lV8nHG9EwR1gALGa5F7gpkjI&_nc_zt=23&_nc_ht=scontent.ftgu2-2.fna&_nc_gid=9nznnTo5vJ8b9ldgDx1vXw&_nc_ss=7b2a8&oh=00_Af4GYjPnQecbgvrnlL4JwaiW73U31yudqWnaMAUAuSdDtg&oe=69FD62AB",
    "gallery": "",
    "description": "Trigger gamer para celular, ideal para mejorar el control al apuntar, disparar y moverse en juegos móviles. Práctico para Free Fire, PUBG Mobile, Call of Duty Mobile y otros juegos de acción.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-003",
    "name": "Enfriador X112",
    "categories": "Enfriador Gamer para Celular",
    "brand": "X112",
    "price": 400,
    "cost": 250,
    "stock": 2,
    "image": "https://scontent.ftgu2-2.fna.fbcdn.net/v/t39.84726-6/678969681_1863159007733174_8930140486556014096_n.jpg?stp=dst-jpg_s960x960_tt6&_nc_cat=103&ccb=1-7&_nc_sid=92e707&_nc_eui2=AeGxhI97-NJM92kUUWF1RwZ0awEZrbtLW5NrARmtu0tbk9DqMP09lIeReeCPoBA7JfEIZcbp4W5ahJX7az21i7tI&_nc_ohc=ovc6pnU9rwgQ7kNvwFfKyxV&_nc_oc=AdpRlWWanDrYmaiG89EucQY8q6AjOFO1ASdld4-gaPwUl3ZAXKoqSa5FzMpMYe_7f5M&_nc_zt=14&_nc_ht=scontent.ftgu2-2.fna&_nc_gid=7bJJa9204AqiiFdLg8sd4w&_nc_ss=7b2a8&oh=00_Af77IRQCxtgOu4A0iQdZ4zXKjI6gqOPlKBj9EGP0n00wUA&oe=69FD770A",
    "gallery": "",
    "description": "Enfriador para celular, ayuda a reducir la temperatura del equipo durante partidas largas, manteniendo un mejor rendimiento y mayor comodidad al jugar.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-005",
    "name": "Dedales o Fundas para Dedos Gamer V2 para Celular",
    "categories": "Dedales",
    "brand": "",
    "price": 50,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Dedales gamer versión V2 para celular, con tacto cómodo y buena respuesta en pantalla. Recomendados para quienes buscan más control, mejor deslizamiento y comodidad durante partidas largas.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-006",
    "name": "Dedales Gamer Pro Hilo de Plata para Celular",
    "categories": "Dedales",
    "brand": "",
    "price": 190,
    "cost": 0,
    "stock": 0,
    "image": "",
    "gallery": "",
    "description": "Dedales Memo para gaming móvil, diseñados para mejorar la sensibilidad al tocar la pantalla y mantener un deslizamiento más estable. Ideales para jugadores de Free Fire, PUBG Mobile, COD Mobile y juegos similares.",
    "promos": "",
    "updatedAt": "2026-05-10T23:02:09.514Z",
    "active": true
  },
  {
    "id": "SDC-004",
    "name": "Guantes Hilo de Plata – Marca Memo",
    "categories": "Gamer Móvil",
    "brand": "MEMO",
    "price": 360,
    "cost": 110,
    "stock": 2,
    "image": "https://accmovilhn.com/wp-content/uploads/2022/02/Glovem.jpg",
    "gallery": "",
    "description": "Guantes Memo para gaming móvil, pensados para mayor comodidad, mejor agarre y menos sudor al jugar. Ayudan a mantener un toque más limpio y preciso en la pantalla durante partidas largas.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-007",
    "name": "Enfriador Memo CX15 PRO | Cooler Magnético para Celular",
    "categories": "Enfriador Gamer para Celular",
    "brand": "MEMO",
    "price": 850,
    "cost": 0,
    "stock": 1,
    "image": "https://cdn2.blanxer.com/uploads/66fee8ef11201b5cb450cf97/product_image-img_0537-1238.webp",
    "gallery": "",
    "description": "Enfriador CX15 para celular, práctico para controlar el calentamiento del teléfono durante juegos o uso intenso. Ideal para mantener el dispositivo más fresco y estable.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-008",
    "name": "Audifonos QKZ",
    "categories": "Audio",
    "brand": "QKZ",
    "price": 0,
    "cost": 0,
    "stock": 0,
    "image": "",
    "gallery": "",
    "description": "Audífonos QKZ con cable, ideales para escuchar música, jugar y realizar llamadas con sonido claro. Diseño cómodo para uso diario y buena experiencia de audio.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-009",
    "name": "Audifonos Tipo C",
    "categories": "Audio",
    "brand": "",
    "price": 0,
    "cost": 0,
    "stock": 0,
    "image": "",
    "gallery": "",
    "description": "Audífonos Tipo C para celulares con entrada USB-C, ideales para música, llamadas, videos y juegos. Una opción práctica para teléfonos que no tienen entrada auxiliar 3.5 mm.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-010",
    "name": "Adaptador MicroSD – USB 2.0",
    "categories": "Tecnología / Accesorios",
    "brand": "",
    "price": 60,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Adaptador para tarjeta MicroSD, útil para convertir una microSD a tamaño SD y facilitar la transferencia de fotos, videos, documentos y otros archivos en computadoras o lectores compatibles.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-011",
    "name": "Secador de Zapatos 2 en 1 (Seca y Quita el Mal Olor) – Temporizador hasta 120 min",
    "categories": "Hogar",
    "brand": "",
    "price": 350,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Secador de zapatos práctico para ayudar a eliminar humedad del calzado después de lluvia, lavado o uso diario. Ideal para mantener los zapatos más secos, cómodos y con mejor olor.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-012",
    "name": "Termo Stanley Rosado",
    "categories": "Termos / Hogar",
    "brand": "Stanley",
    "price": 0,
    "cost": 0,
    "stock": 0,
    "image": "",
    "gallery": "",
    "description": "Termo estilo Stanley color rosado, ideal para llevar bebidas frías o calientes por más tiempo. Diseño moderno, práctico y bonito para uso diario, trabajo, estudio, viajes o gimnasio.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-013",
    "name": "Enfriador PRO para Celular – Juega sin LAG, sin Calor",
    "categories": "Enfriador Gamer para Celular",
    "brand": "",
    "price": 360,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Enfriador PRO para celular, ideal para ayudar a controlar el calentamiento durante juegos, transmisiones o uso intenso. Recomendado para mantener el equipo más fresco y cómodo en partidas largas.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-014",
    "name": "Enfriador o Cooler Gamer para Celular",
    "categories": "Enfriador Gamer para Celular",
    "brand": "",
    "price": 150,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Cooler gamer para celular, práctico para reducir la temperatura del teléfono mientras jugás. Ayuda a mantener un mejor rendimiento y mayor comodidad durante sesiones prolongadas.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-015",
    "name": "Dedales SARAFOX - Hilo de Plata",
    "categories": "Dedales",
    "brand": "Sarafox",
    "price": 400,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Dedales SARAFOX con hilo de plata para gaming móvil, diseñados para brindar mejor sensibilidad, deslizamiento y precisión en pantalla. Ideales para Free Fire, PUBG Mobile, COD Mobile y juegos táctiles.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-016",
    "name": "Dedales V2 para Gaming Móvil – Precisión y Comodidad",
    "categories": "Dedales",
    "brand": "",
    "price": 90,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Dedales V2 para gaming móvil, cómodos y ligeros para mejorar el control de los dedos en pantalla. Ayudan a reducir el sudor y facilitan movimientos más suaves durante la partida.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-017",
    "name": "Gamepad con Cooler para Celular | Android & iOS",
    "categories": "Controles / Gamepad",
    "brand": "",
    "price": 490,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Gamepad con cooler para celular, compatible con Android y iOS según el equipo. Combina mejor agarre, controles físicos y enfriamiento para jugar con más comodidad.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-018",
    "name": "Gamepad MEMO para Celular 4 Gatillos Personalizables Android & iOS",
    "categories": "Controles / Gamepad",
    "brand": "MEMO",
    "price": 400,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Gamepad MEMO para celular con 4 gatillos personalizables, pensado para juegos de acción y disparos. Brinda mejor control, agarre firme y una experiencia más cómoda en Android y iOS.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-019",
    "name": "GAMEPAD CON COOLER Y JOYSTICK",
    "categories": "Controles / Gamepad",
    "brand": "",
    "price": 300,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Gamepad con cooler y joystick para celular, ideal para quienes buscan mejor control y comodidad al jugar. Su diseño ayuda a sujetar mejor el teléfono y mantenerlo más fresco.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-020",
    "name": "Control PRO Inalámbrico Bluetooth Android / iOS / PC / Switch Turbo + Macro",
    "categories": "Controles / Gamepad",
    "brand": "",
    "price": 490,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Control PRO inalámbrico Bluetooth para Android, iOS, PC y Nintendo Switch. Incluye funciones Turbo y Macro para una experiencia más completa en juegos compatibles.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-021",
    "name": "Control Gamer con Soporte para Celular",
    "categories": "Controles / Gamepad",
    "brand": "",
    "price": 420,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Control gamer con soporte para celular, ideal para jugar con mejor agarre y mayor precisión. Su soporte permite colocar el teléfono de forma cómoda para partidas largas.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-022",
    "name": "Mousepad Xtech Rosa con Soporte de Muñeca 23×18cm",
    "categories": "Mousepad",
    "brand": "Xtech",
    "price": 150,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Mousepad Xtech color rosa con soporte de muñeca, tamaño 23×18 cm. Brinda una superficie cómoda para el mouse y ayuda a descansar la muñeca durante estudio, oficina o gaming casual.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-023",
    "name": "Tira de Esponja para Puertas y Ventanas 70cm Anti Polvo e Insectos",
    "categories": "Hogar",
    "brand": "",
    "price": 80,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Tira de esponja para puertas y ventanas de 70 cm, útil para ayudar a bloquear polvo, insectos y corrientes de aire. Ideal para mejorar el sellado de espacios en el hogar.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-024",
    "name": "Fuente de Agua para Gato o Perro 3L USB + Filtro",
    "categories": "Mascotas",
    "brand": "",
    "price": 270,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Fuente de agua para gato o perro de 3 litros con conexión USB y filtro. Mantiene el agua en movimiento para incentivar a las mascotas a beber con mayor frecuencia.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-025",
    "name": "Funda Protectora para Refrigeradora / Lavadora (Anti Polvo) + Bolsillos",
    "categories": "Hogar",
    "brand": "",
    "price": 150,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Funda protectora para refrigeradora o lavadora, ideal para ayudar a proteger contra polvo y salpicaduras. Incluye bolsillos laterales para guardar artículos pequeños del hogar.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-026",
    "name": "Funda para Moto Impermeable Metalizada 140×240cm (Protección Sol/Lluvia/Polvo)",
    "categories": "Hogar / Automotriz",
    "brand": "",
    "price": 200,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Funda para moto impermeable metalizada de 140×240 cm, diseñada para proteger contra sol, lluvia y polvo. Práctica para cuidar la motocicleta cuando permanece estacionada.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-027",
    "name": "Juego de Destornilladores de Precisión 115 en 1 (PC y Celular)",
    "categories": "Herramientas",
    "brand": "",
    "price": 300,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Juego de destornilladores de precisión 115 en 1, ideal para reparación de celulares, computadoras, laptops, consolas y electrónicos pequeños. Incluye puntas variadas para diferentes trabajos.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-028",
    "name": "Cosmetiquera con Espejo LED | 3 tipos de luz (Natural/Fría/Cálida)",
    "categories": "Belleza",
    "brand": "",
    "price": 290,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Cosmetiquera con espejo LED y 3 tipos de luz: natural, fría y cálida. Perfecta para organizar maquillaje y retocarse con mejor iluminación en casa o de viaje.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-029",
    "name": "Afilador de Cuchillos – 3 Niveles",
    "categories": "Cocina / Hogar",
    "brand": "",
    "price": 100,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Afilador de cuchillos de 3 niveles, práctico para recuperar y mantener el filo de cuchillos de cocina. Compacto, fácil de usar y útil para el hogar.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-030",
    "name": "Mouse Gamer X12 – 3200DPI",
    "categories": "Mouse / Tecnología",
    "brand": "",
    "price": 300,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Mouse gamer X12 de 3200 DPI, ideal para juegos, estudio y uso diario en computadora. Diseño cómodo con buen agarre para movimientos más precisos.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-031",
    "name": "Memoria USB 3.2 – 256GB",
    "categories": "Memorias USB",
    "brand": "MEMO",
    "price": 1050,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Memoria USB 3.2 de 256GB, ideal para guardar fotos, videos, documentos, música y respaldos importantes. Portátil, práctica y fácil de usar en computadoras compatibles.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-032",
    "name": "Memoria USB 3.2 – 128GB",
    "categories": "Memorias USB",
    "brand": "MEMO",
    "price": 620,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Memoria USB 3.2 de 128GB, excelente para transportar archivos, tareas, fotos y videos. Una opción práctica para estudio, trabajo y respaldo de información.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-033",
    "name": "Memoria USB 3.2 – 64GB",
    "categories": "Memorias USB",
    "brand": "MEMO",
    "price": 320,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Memoria USB 3.2 de 64GB, compacta y útil para guardar documentos, música, fotos y archivos de uso diario. Ideal para estudiantes, oficina y respaldo rápido.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-034",
    "name": "Memoria USB 3.2 – 32GB",
    "categories": "Memorias USB",
    "brand": "MEMO",
    "price": 240,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Memoria USB 3.2 de 32GB, práctica para transferir y guardar documentos, tareas, fotos y archivos pequeños. Fácil de llevar y usar en computadoras compatibles.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-035",
    "name": "Memoria USB - 16GB",
    "categories": "Memorias USB",
    "brand": "MEMO",
    "price": 190,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Memoria USB de 16GB, ideal para guardar documentos, tareas, música y archivos personales. Una opción económica y práctica para uso diario.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-036",
    "name": "Memoria MicroSD 256GB – V30 / U3 / A1",
    "categories": "Memorias MicroSD",
    "brand": "MEMO",
    "price": 1350,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Memoria MicroSD 256GB V30 / U3 / A1, recomendada para celulares, cámaras y dispositivos compatibles. Ideal para ampliar almacenamiento y guardar fotos, videos y aplicaciones.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-037",
    "name": "Maxell MicroSD 128GB – Alta Velocidad",
    "categories": "Memorias MicroSD",
    "brand": "Maxell",
    "price": 920,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Memoria Maxell MicroSD 128GB de alta velocidad, ideal para ampliar almacenamiento en celulares, cámaras y otros equipos compatibles. Perfecta para fotos, videos y archivos.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-038",
    "name": "Maxell MicroSD 64GB – Clase 10",
    "categories": "Memorias MicroSD",
    "brand": "Maxell",
    "price": 450,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Memoria Maxell MicroSD 64GB Clase 10, práctica para celulares, cámaras y dispositivos compatibles. Buena opción para guardar fotos, música, videos y documentos.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-039",
    "name": "Maxell MicroSD 32GB – Clase 10",
    "categories": "Memorias MicroSD",
    "brand": "Maxell",
    "price": 290,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Memoria Maxell MicroSD 32GB Clase 10, ideal para ampliar almacenamiento en equipos compatibles. Útil para fotos, música, documentos y archivos de uso diario.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-040",
    "name": "Maxell MicroSD 16GB – Clase 10",
    "categories": "Memorias MicroSD",
    "brand": "Maxell",
    "price": 230,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Memoria Maxell MicroSD 16GB Clase 10, opción práctica para guardar archivos básicos, música, fotos y documentos en celulares o dispositivos compatibles.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  },
  {
    "id": "SDC-041",
    "name": "Ubicación Tienda SD-COMAYAGUA (Piedras Bonitas) | WhatsApp 3151-7755",
    "categories": "Tienda / Información",
    "brand": "",
    "price": 0,
    "cost": 0,
    "stock": 1,
    "image": "",
    "gallery": "",
    "description": "Publicación informativa con la ubicación de SD-COMAYAGUA en Piedras Bonitas y contacto por WhatsApp 3151-7755. Sirve para orientar al cliente y facilitar la visita a la tienda.",
    "promos": "",
    "updatedAt": "2026-05-10T04:25:23",
    "active": true
  }
];

window.SDC_PLACEHOLDERS = {
  gamer:'assets/placeholders/gamer.svg',
  tecnología:'assets/placeholders/tecnologia.svg',
  tecnologia:'assets/placeholders/tecnologia.svg',
  hogar:'assets/placeholders/hogar.svg',
  cocina:'assets/placeholders/hogar.svg',
  default:'assets/placeholders/no-image.svg'
};
