const CACHE_NAME = 'sd-comayagua-pos-v1.3.1';
const ASSETS = [
  './',
  './index.html',
  './app.html',
  './manifest.json',
  './css/styles.css',
  './css/themes.css',
  './css/mobile.css',
  './css/catalog-polish.css',
  './css/print.css',
  './js/config.js',
  './js/app.js',
  './js/assets-enhancer.js',
  './js/state.js',
  './js/data.js',
  './js/sheets.js',
  './js/sync.js',
  './js/products.js',
  './js/inventory.js',
  './js/cart.js',
  './js/quotes.js',
  './js/sales.js',
  './js/customers.js',
  './js/reports.js',
  './js/backup.js',
  './js/whatsapp.js',
  './js/receipts.js',
  './js/ui.js',
  './js/utils.js',
  './js/validators.js',
  './assets/categorias/accesorio.svg',
  './assets/categorias/accesorios.svg',
  './assets/categorias/adaptador-de-microsd.svg',
  './assets/categorias/adaptador-micro-sd.svg',
  './assets/categorias/adaptador-microsd.svg',
  './assets/categorias/adaptador.svg',
  './assets/categorias/adaptadores.svg',
  './assets/categorias/agotados.svg',
  './assets/categorias/audifono.svg',
  './assets/categorias/audifonos-c.svg',
  './assets/categorias/audifonos-qkz.svg',
  './assets/categorias/audifonos-tipo-c.svg',
  './assets/categorias/audifonos.svg',
  './assets/categorias/audio.svg',
  './assets/categorias/auriculares.svg',
  './assets/categorias/belleza.svg',
  './assets/categorias/cable.svg',
  './assets/categorias/cables.svg',
  './assets/categorias/cargador.svg',
  './assets/categorias/cargadores.svg',
  './assets/categorias/categoria.svg',
  './assets/categorias/celulares.svg',
  './assets/categorias/cocina.svg',
  './assets/categorias/cooler.svg',
  './assets/categorias/coolers.svg',
  './assets/categorias/dedales-memo.svg',
  './assets/categorias/dedales-v1.svg',
  './assets/categorias/dedales-v2.svg',
  './assets/categorias/dedales.svg',
  './assets/categorias/enfriador-memo.svg',
  './assets/categorias/enfriador-x112.svg',
  './assets/categorias/enfriador.svg',
  './assets/categorias/enfriadores.svg',
  './assets/categorias/gamer-movil.svg',
  './assets/categorias/gamer.svg',
  './assets/categorias/gaming.svg',
  './assets/categorias/gatillo.svg',
  './assets/categorias/gatillos.svg',
  './assets/categorias/general.svg',
  './assets/categorias/guante.svg',
  './assets/categorias/guantes-memo.svg',
  './assets/categorias/guantes.svg',
  './assets/categorias/herramienta.svg',
  './assets/categorias/herramientas.svg',
  './assets/categorias/hogar.svg',
  './assets/categorias/juegos.svg',
  './assets/categorias/limpieza.svg',
  './assets/categorias/mas-vendidos.svg',
  './assets/categorias/memoria.svg',
  './assets/categorias/memorias.svg',
  './assets/categorias/micro-sd.svg',
  './assets/categorias/microsd.svg',
  './assets/categorias/nuevo.svg',
  './assets/categorias/ofertas.svg',
  './assets/categorias/otro.svg',
  './assets/categorias/otros.svg',
  './assets/categorias/promociones.svg',
  './assets/categorias/secador-de-zapatos.svg',
  './assets/categorias/secador-zapatos.svg',
  './assets/categorias/stock-bajo.svg',
  './assets/categorias/tecnologia.svg',
  './assets/categorias/termo-stanley.svg',
  './assets/categorias/termo.svg',
  './assets/categorias/termos.svg',
  './assets/categorias/tipo-c-audio.svg',
  './assets/categorias/tipo-c.svg',
  './assets/categorias/todas.svg',
  './assets/categorias/trigger.svg',
  './assets/categorias/zapato.svg',
  './assets/categorias/zapatos.svg',
  './assets/icons/icon.svg',
  './assets/logo-sdc-2026.png',
  './assets/logo-sdc-2026.svg',
  './assets/logo-sdc-receipt.png',
  './assets/logo-sdc-receipt.svg',
  './assets/logo-sdc.png',
  './assets/logo-sdc.svg',
  './assets/placeholders/product.svg'
];
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(ASSETS)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;
  event.respondWith(caches.match(req).then(cached => cached || fetch(req).then(res => {
    const copy = res.clone(); caches.open(CACHE_NAME).then(cache => cache.put(req, copy)); return res;
  }).catch(() => caches.match('./app.html'))));
});
